#[derive(Debug, PartialEq)]
pub enum Instruction {
    Cls,
    Ret,
    Jump(u16),
    Call(u16),
    SkipEq(u8, u8),
    SkipNotEq(u8, u8),
    SkipRegEq(u8, u8),
    Load(u8, u8),
    Add(u8, u8),
    LoadReg(u8, u8),
    Or(u8, u8),
    And(u8, u8),
    Xor(u8, u8),
    AddReg(u8, u8),
    SubReg(u8, u8),
    Shr(u8, u8),
    Subn(u8, u8),
    Shl(u8, u8),
    SkipRegNotEq(u8, u8),
    LoadI(u16),
    JumpOffset(u16),
    Rand(u8, u8),
    Draw(u8, u8, u8),
    SkipIfPressed(u8),
    SkipIfNotPressed(u8),
    LoadRegFromDelay(u8),
    WaitForKey(u8),
    LoadDelayFromReg(u8),
    LoadSoundFromReg(u8),
    AddIndex(u8),
    LoadFont(u8),
    Bcd(u8),
    DumpRegs(u8),
    FillRegs(u8),
}
